language: python
python:
    - 3.8

before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest

env: PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR

install:
    - pip install ".[test]" . # install package + test dependencies

script: pytest # run tests



